### PR TITLE
Draft of smarter dev analysis for review

### PR DESCRIPTION
**Pull request by ptoman-pa**
# Purpose
Improves "completeness" for finding development aka non-production systems. We care about non-production systems because identifying them is a precondition for automatic remediation.

# Impact
The revision triples the true positives (from 4k to 13k in test data) by picking up on examples like:
* {"environment": "stg"}
* {"ENV": "nonprod"}
* test.example.com:8443

It also eliminates the previous 20% false positive rate (1k of 5k) by not flagging examples like:
* devops
* devanshi.lastname
* {"team": "named-dev", "env": "prod"}

# Technical overview
* Introduces script "InferWhetherServiceIsDev", including tests & docs, which:
  1) checks public indicators as well as internal tags
  2) checks internal tags for many more terms
  3) checks more precisely only the tags that are related to the deployment "environment".
* Alters playbooks to use "InferWhetherServiceIsDev"
  * Enrichment - Adds a final stage that executes script
  * ASM Alert - Alters the "Meets automated remediation requirements?" task to use result

# Testing plan
* Unit tests (see file)
* Verified script can execute on its own within alert warroom: `!InferWhetherServiceIsDev active_classifications=${ASM.ExternalService.active_classifications} asm_tags=${alert.asmtags}`
* Verified revised playbooks successfully execute against two examples:
   * inferred "dev": see callu alert 743
   * inferred "can't tell": see callu alert 1566

### CODE REVIEW

**Comment by johnnywilkes** [comment]
General question: Is to goal to have some certainty that the service is dev or just non-prd?  They are somewhat different

**Comment by johnnywilkes** [comment]
`!InferWhetherIsDev_jw active_classifications=${subplaybook-97.ASM.ExternalService.active_classifications} asm_tags=${alert.asmtags}`
^^Example command to test in war room for newest run of "Cortex ASM - ASM Alert" playbook

**Comment by johnnywilkes** [comment]
from linting:
```
############################
 unit-tests coverage report
############################
Name                                                                                               Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------
Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py      48     15    69%
----------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                 48     15    69%

Flake8       - [FAIL]
XSOAR linter - [PASS]
Bandit       - [PASS]
Mypy         - [FAIL]
Vulture      - [PASS]
Pytest       - [PASS]
Pylint       - [PASS]
Pwsh analyze - [SKIPPED]
Pwsh test    - [SKIPPED]

Passed Unit-tests:
  - Package: InferWhetherServiceIsDev
      - Image: demisto/python3:3.10.9.42476
         - InferWhetherServiceIsDev_test.py::test_canonicalize
         - InferWhetherServiceIsDev_test.py::test_is_dev_according_to_key_value_pairs
         - InferWhetherServiceIsDev_test.py::test_is_dev_according_to_classifications

###############
 Flake8 errors 
###############

InferWhetherServiceIsDev
InferWhetherServiceIsDev.py:1:1: F401 'json' imported but unused
InferWhetherServiceIsDev.py:3:1: F401 'base64.b64decode' imported but unused
InferWhetherServiceIsDev.py:40:131: E501 line too long (133 > 130 characters)
InferWhetherServiceIsDev.py:41:131: E501 line too long (153 > 130 characters)
InferWhetherServiceIsDev_test.py:3:1: E302 expected 2 blank lines, found 1
InferWhetherServiceIsDev_test.py:9:1: E302 expected 2 blank lines, found 1
InferWhetherServiceIsDev_test.py:19:1: E302 expected 2 blank lines, found 1
InferWhetherServiceIsDev_test.py:23:91: W292 no newline at end of file


#############
 Mypy errors 
#############

InferWhetherServiceIsDev
/Users/jwilkes/Code/pamela-content/content/Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py:48:36: error:
Argument 1 to "_canonicalize_string" has incompatible type "Optional[Any]";
expected "str"  [arg-type]
            key = _canonicalize_string(kv_pair.get("Key"))
                                       ^~~~~~~~~~~~~~~~~~
/Users/jwilkes/Code/pamela-content/content/Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py:49:38: error:
Argument 1 to "_canonicalize_string" has incompatible type "Optional[Any]";
expected "str"  [arg-type]
            value = _canonicalize_string(kv_pair.get("Value"))
                                         ^~~~~~~~~~~~~~~~~~~~
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by johnnywilkes** [comment]
> General question: Is to goal to have some certainty that the service is dev or just non-prd? They are somewhat different

Pamela to add more information to script description and pack README

**Comment by ptoman-pa** [comment]
Revised. 

@johnnywilkes I'd appreciate your eyes one more time, since it's more complex now. additionally, would you want to paste final linting/etc. on this, or should I close it and we open against the full repo and have it run automatically? (I'd like to wait for a second PR to invest in setting up VSCode locally since PyCharm is my pre-existing daily driver)

**Comment by johnnywilkes** [comment]
Adding here so I don't forget.  We need to create the new field and add to PR also

**Comment by johnnywilkes** [comment]
@ptoman-pa here it the most up to date lint report:
```
############################
 unit-tests coverage report
############################
Name                                                                                               Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------
Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py      49     16    67%
----------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                 49     16    67%

Flake8       - [FAIL]
XSOAR linter - [FAIL]
Bandit       - [PASS]
Mypy         - [PASS]
Vulture      - [PASS]
Pytest       - [FAIL]
Pylint       - [PASS]
Pwsh analyze - [SKIPPED]
Pwsh test    - [SKIPPED]

############
 Unit Tests 
############

Passed Unit-tests:
  - Package: InferWhetherServiceIsDev
      - Image: demisto/python3:3.10.9.42476
         - InferWhetherServiceIsDev_test.py::test_canonicalize

Failed Unit-tests:
  - Package: InferWhetherServiceIsDev
         - InferWhetherServiceIsDev_test.py::test_is_dev_according_to_key_value_pairs
      - Image: demisto/python3:3.10.9.42476
           Error: def test_is_dev_according_to_key_value_pairs():
                          from InferWhetherServiceIsDev import is_dev_according_to_key_value_pairs

                          assert is_dev_according_to_key_value_pairs([{"Key": "env", "Source":
                  "AWS", "Value": "dev"},
                                                                      {"Key": "Name", "Source":
                  "AWS", "Value": "rdp_server"},
                                                                      {"Key": "test", "Source":
                  "AWS", "Value": ""}])
                          assert is_dev_according_to_key_value_pairs([{"Key": "ENVIRONMENT",
                  "Source": "AWS", "Value": "TEST"}])
                          assert is_dev_according_to_key_value_pairs([{"Key": "Stage", "Source":
                  "AWS", "Value": "status - preprod"}])
                  >       assert not is_dev_according_to_key_value_pairs([{"Key": "env", "Source":
                  "AWS", "Value": "prod"}])
                  E       AssertionError: assert not (False, [])
                  E        +  where (False, []) = <function is_dev_according_to_key_value_pairs at
                  0x400c743b50>([{'Key': 'env', 'Source': 'AWS', 'Value': 'prod'}])

                  InferWhetherServiceIsDev_test.py:19: AssertionError


         - InferWhetherServiceIsDev_test.py::test_is_dev_according_to_classifications
      - Image: demisto/python3:3.10.9.42476
           Error: def test_is_dev_according_to_classifications():
                          from InferWhetherServiceIsDev import is_dev_according_to_classifications

                          assert is_dev_according_to_classifications(["SshServer",
                  "DevelopmentEnvironment"])
                  >       assert not is_dev_according_to_classifications(["RdpServer",
                  "SelfSignedCertificate"])
                  E       AssertionError: assert not (False, [])
                  E        +  where (False, []) = <function is_dev_according_to_classifications at
                  0x400c743be0>(['RdpServer', 'SelfSignedCertificate'])

                  InferWhetherServiceIsDev_test.py:27: AssertionError



###############
 Flake8 errors 
###############

InferWhetherServiceIsDev
InferWhetherServiceIsDev.py:59:26: E127 continuation line over-indented for visual indent
InferWhetherServiceIsDev.py:59:69: E261 at least two spaces before inline comment
InferWhetherServiceIsDev.py:60:26: E127 continuation line over-indented for visual indent
InferWhetherServiceIsDev.py:61:26: E127 continuation line over-indented for visual indent
InferWhetherServiceIsDev.py:145:131: E501 line too long (164 > 130 characters)


#####################
 Xsoar_linter errors 
#####################

InferWhetherServiceIsDev
/Users/jwilkes/Code/pamela-content/content/Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py:145:12: E9002 main: Print is found, Please remove all prints from the code.
/Users/jwilkes/Code/pamela-content/content/Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev/InferWhetherServiceIsDev.py:147:12: E9002 main: Print is found, Please remove all prints from the code.

#########
 Summary 
#########
Packages: 1
Packages PASS: 0
Packages FAIL: 1
Packages WARNING (can either PASS or FAIL): 0

Failed packages:
   - InferWhetherServiceIsDev
```

**Comment by johnnywilkes** [comment]
@ptoman-pa , i am really sorry about this but I think you used an older version of the repo/playbook because of your instructions in https://gitlab.xdr.pan.local/xdr/xpanse/machine-learning-projects/data-science-experiments/-/tree/master/2022-08-afr/afr-is-dev/productionization and I should have correctly you earlier.

You want to set `git remote add upstream https://github.com/demisto/content.git` and update your local repo with
```
git fetch upstream
git rebase upstream/master
```
at least before creating branch.  Let me know if you want me to clean this up for you


Also, i think this best to do the PR again another fork like John's, mine or Chait because that way we make sure it is good before the final PR to the Tel Aviv content teams.  Either of us to run lint commands with:
`demisto-sdk lint -i /Users/jwilkes/Code/pamela-content/content/Packs/CortexAttackSurfaceManagement/Scripts/InferWhetherServiceIsDev`

**Comment by ptoman-pa** [comment]
Updates to branch: 
* included the "ASM - Dev Check" IncidentField 
* rebased against upstream master
* flattened everything into a single commit for easy cherry-picking
* installed & configured VSCode & ran all the linting (ok), coverage (72% because it's not clear to me how to test for a context side effect as output with the mocking library), and tests (ok)
* slightly updated the logic to (a) remove the explanations which were only being used in a print statement that is disallowed, and (b) detect conflicting dev PLUS prod environments and avoid setting them to "is dev".

I'm closing this PR (the diff is massive because now this branch is ahead of the target), but the diff is visible at: https://github.com/demisto/content/compare/master...ptoman-pa:content:plt-dev-script?expand=1

**Pull request closed without merging**
